import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, json, boolean } from "drizzle-orm/mysql-core";

/**
 * Core user table with standalone JWT authentication
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  passwordHash: varchar("passwordHash", { length: 256 }).notNull(),
  name: text("name"),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Refresh tokens for session management
 */
export const refreshTokens = mysqlTable("refresh_tokens", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  token: varchar("token", { length: 512 }).notNull().unique(),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RefreshToken = typeof refreshTokens.$inferSelect;
export type InsertRefreshToken = typeof refreshTokens.$inferInsert;

/**
 * Trading signals generated by the AI system
 */
export const tradingSignals = mysqlTable("trading_signals", {
  id: int("id").autoincrement().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  signalType: mysqlEnum("signalType", ["strong_buy", "buy", "hold", "sell", "strong_sell"]).notNull(),
  confidence: decimal("confidence", { precision: 5, scale: 4 }).notNull(),
  regime: mysqlEnum("regime", ["trend_up", "trend_down", "mean_reversion", "high_volatility", "low_volatility"]).notNull(),
  suggestedTp: int("suggestedTp").notNull(), // in ticks
  suggestedSl: int("suggestedSl").notNull(), // in ticks
  entryPrice: decimal("entryPrice", { precision: 10, scale: 2 }),
  features: json("features"), // JSON object with feature values
  modelPredictions: json("modelPredictions"), // JSON with individual model predictions
  executed: boolean("executed").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type TradingSignal = typeof tradingSignals.$inferSelect;
export type InsertTradingSignal = typeof tradingSignals.$inferInsert;

/**
 * Market regime history for tracking regime transitions
 */
export const regimeHistory = mysqlTable("regime_history", {
  id: int("id").autoincrement().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  regime: mysqlEnum("regime", ["trend_up", "trend_down", "mean_reversion", "high_volatility", "low_volatility"]).notNull(),
  confidence: decimal("confidence", { precision: 5, scale: 4 }).notNull(),
  duration: int("duration"), // duration in bars/minutes
  vixLevel: decimal("vixLevel", { precision: 6, scale: 2 }),
  gexLevel: decimal("gexLevel", { precision: 12, scale: 2 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type RegimeHistory = typeof regimeHistory.$inferSelect;
export type InsertRegimeHistory = typeof regimeHistory.$inferInsert;

/**
 * Open and closed positions for risk management
 */
export const positions = mysqlTable("positions", {
  id: int("id").autoincrement().primaryKey(),
  signalId: int("signalId"),
  direction: mysqlEnum("direction", ["long", "short"]).notNull(),
  entryPrice: decimal("entryPrice", { precision: 10, scale: 2 }).notNull(),
  exitPrice: decimal("exitPrice", { precision: 10, scale: 2 }),
  quantity: int("quantity").notNull(),
  stopLoss: decimal("stopLoss", { precision: 10, scale: 2 }).notNull(),
  takeProfit: decimal("takeProfit", { precision: 10, scale: 2 }).notNull(),
  status: mysqlEnum("status", ["open", "closed", "cancelled"]).default("open").notNull(),
  pnl: decimal("pnl", { precision: 12, scale: 2 }),
  pnlPercent: decimal("pnlPercent", { precision: 8, scale: 4 }),
  openedAt: timestamp("openedAt").defaultNow().notNull(),
  closedAt: timestamp("closedAt"),
  closeReason: mysqlEnum("closeReason", ["tp_hit", "sl_hit", "manual", "timeout", "signal"]),
});

export type Position = typeof positions.$inferSelect;
export type InsertPosition = typeof positions.$inferInsert;

/**
 * Daily performance statistics
 */
export const dailyStats = mysqlTable("daily_stats", {
  id: int("id").autoincrement().primaryKey(),
  date: timestamp("date").notNull(),
  totalTrades: int("totalTrades").default(0).notNull(),
  winningTrades: int("winningTrades").default(0).notNull(),
  losingTrades: int("losingTrades").default(0).notNull(),
  winRate: decimal("winRate", { precision: 5, scale: 4 }),
  grossPnl: decimal("grossPnl", { precision: 12, scale: 2 }).default("0").notNull(),
  netPnl: decimal("netPnl", { precision: 12, scale: 2 }).default("0").notNull(),
  maxDrawdown: decimal("maxDrawdown", { precision: 12, scale: 2 }).default("0").notNull(),
  sharpeRatio: decimal("sharpeRatio", { precision: 6, scale: 4 }),
  avgWin: decimal("avgWin", { precision: 12, scale: 2 }),
  avgLoss: decimal("avgLoss", { precision: 12, scale: 2 }),
  largestWin: decimal("largestWin", { precision: 12, scale: 2 }),
  largestLoss: decimal("largestLoss", { precision: 12, scale: 2 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type DailyStats = typeof dailyStats.$inferSelect;
export type InsertDailyStats = typeof dailyStats.$inferInsert;

/**
 * System configuration settings
 */
export const systemConfig = mysqlTable("system_config", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  maxDailyLoss: decimal("maxDailyLoss", { precision: 12, scale: 2 }).default("2000").notNull(),
  maxPositionSize: int("maxPositionSize").default(5).notNull(),
  maxDailyTrades: int("maxDailyTrades").default(10).notNull(),
  tradingStartTime: varchar("tradingStartTime", { length: 8 }).default("15:30").notNull(),
  tradingEndTime: varchar("tradingEndTime", { length: 8 }).default("22:00").notNull(),
  defaultTp: int("defaultTp").default(8).notNull(),
  defaultSl: int("defaultSl").default(5).notNull(),
  notificationsEnabled: boolean("notificationsEnabled").default(true).notNull(),
  telegramEnabled: boolean("telegramEnabled").default(false).notNull(),
  autoTradeEnabled: boolean("autoTradeEnabled").default(false).notNull(),
  riskPerTrade: decimal("riskPerTrade", { precision: 5, scale: 4 }).default("0.01").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SystemConfig = typeof systemConfig.$inferSelect;
export type InsertSystemConfig = typeof systemConfig.$inferInsert;

/**
 * Feature importance tracking
 */
export const featureImportance = mysqlTable("feature_importance", {
  id: int("id").autoincrement().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  featureName: varchar("featureName", { length: 128 }).notNull(),
  importance: decimal("importance", { precision: 10, scale: 6 }).notNull(),
  category: mysqlEnum("category", ["price", "volume", "orderflow", "options", "technical", "regime"]).notNull(),
  modelType: varchar("modelType", { length: 64 }).notNull(),
});

export type FeatureImportance = typeof featureImportance.$inferSelect;
export type InsertFeatureImportance = typeof featureImportance.$inferInsert;

/**
 * Optimization surface data for 3D visualization
 */
export const optimizationSurface = mysqlTable("optimization_surface", {
  id: int("id").autoincrement().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  tpTicks: int("tpTicks").notNull(),
  slTicks: int("slTicks").notNull(),
  expectedValue: decimal("expectedValue", { precision: 10, scale: 4 }).notNull(),
  winRate: decimal("winRate", { precision: 5, scale: 4 }),
  profitFactor: decimal("profitFactor", { precision: 8, scale: 4 }),
  sampleSize: int("sampleSize"),
});

export type OptimizationSurface = typeof optimizationSurface.$inferSelect;
export type InsertOptimizationSurface = typeof optimizationSurface.$inferInsert;

/**
 * System notifications
 */
export const notifications = mysqlTable("notifications", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: mysqlEnum("type", ["signal", "risk_alert", "system", "performance", "error"]).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  message: text("message").notNull(),
  severity: mysqlEnum("severity", ["info", "warning", "error", "success"]).default("info").notNull(),
  read: boolean("read").default(false).notNull(),
  data: json("data"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = typeof notifications.$inferInsert;
